#!/usr/bin/python3
"""Factorize given set of numbers in a file to product of two small numbers"""

import sys


def factorize_number(number):
    """Find two small numbers that multiply to give a given number"""
    factors = set()
    for i in range(2, number // 2 + 1):
        if number % i == 0:
            factors.add((i, number // i))
    return factors


def factorize_file(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line)
            factors = factorize_number(number)
            if not factors:
                print(f"{number} is prime")
            else:
                for factor_pair in factors:
                    factor1, factor2 = factor_pair
                    if factor1 <= factor2:  # Ensure unique factorizations
                        print(f"{number}={factor1}*{factor2}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    factorize_file(filename)
