#!/usr/bin/python3

"""
Factorize numbers from a file into two factors p and q.

Usage:
    python factors.py <file>

Where <file> contains one number per line to factor.

Output format:
    n=p*q

Factors p and q don't have to be prime,
but should be the smallest possible factors of n.

Stops after factorizing for 5 seconds.
"""

import sys
import time

start_time = time.time()

with open(sys.argv[1]) as f:
    for line in f:
        n = int(line.strip())

        for i in range(2, int(n**0.5)+1):
            if n % i == 0:
                p = i
                q = n // i
                print(f"{n}={p}*{q}")
                break

        if time.time() - start_time > 5:
            print("Time limit exceeded")
            break
